name: lint_check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install libjpeg8-dev zlib1g-dev
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: 'igdb_indexer'
          use-pylint: false
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true
          extra-pycodestyle-options: "--max-line-length=120"
          extra-black-options: "--line-length=120"
          extra-isort-options: "--profile=black"
